services:
  xxx-ui:
    build: .
    image: xxx-ui
    container_name: xxx-ui
    volumes:
      - db:/etc/x-ui/
      - cert:/root/cert/
    tty: true
    ports:
      - "127.0.0.1:2053:2053"
      - "443:443"
      - "443:443/udp"
    restart: unless-stopped

volumes:
  db:
  cert:
