services:
  xxx-ui:
    build: .
    image: xxx-ui
    container_name: xxx-ui
    volumes:
      - db:/etc/x-ui/
      - cert:/root/cert/
    tty: true
    network_mode: host
    restart: unless-stopped

volumes:
  db:
  cert:
